### ISSUE TITLE
画像の追加

### ISSUE THREAD

**Issue by iwashima-kento** [kawamura-yama/iniad-fake-homepage#12]
index.htmlの背景にINIADの画像を追加する。
余裕があれば背景画像の固定化とcourses.htmlにコースごとのイメージ画像を追加する。

**Comment by iwashima-kento** [comment]
それでは作業を開始します。
回らないお寿司を所望いたします！

Now let's get to work.
I would like sushi that does not turn around!

**Comment by kawamura-yama** [comment]
>回らないお寿司を所望いたします！
こ、これは経費で落ちるのでしょうか？

**Comment by kawamura-yama** [comment]
お、お寿司代は経費で落ちるのでしょうか？

**Comment by tanaka-kei-034** [comment]
完了確認しました
