### ISSUE TITLE
子画面からトップ画面(index.html)に戻るリンクを追加

### ISSUE THREAD

**Issue by kawamura-yama** [kawamura-yama/iniad-fake-homepage#14]
子画面からトップ画面(index.html)に戻るリンクがないと不便に感じました。
各子画面の下の方にトップ画面へのリンクを付けたいと思います。

不要だと思う方は11月30日の18時までにこのIssuesに書き込みお願いします。
18時までにとくに書き込みがない場合は、山中の方でトップ画面へのリンクを追加します。

**Comment by kogashintarou** [comment]
追加に賛成です！

**Comment by kawamura-yama** [comment]
To 古閑さん
賛成のお声ありがとうございます。

修正に対応しました。

【修正内容】
・画面の一番下にトップ画面に戻るリンクを追加(concept.html)
・画面の一番下にトップ画面に戻るリンクを追加(courses.html)
